In [2]:
x,y,z=3,4,5

In [3]:
if (x < (y+z)) and (y < (y+x)) and (z < (y+x)):
    print(True)

True


In [21]:
x = 17
for i in range(2, x):
  if (x % i == 0):
   print(False)
   break
else:
   print(True)

True


In [11]:
import numpy as np
from time import time


np.random.random(3)

tick = time()
print(tick)

sum(1/np.arange(1,101)**2)

np.pi

1666200864.634687


3.141592653589793

In [12]:
arr = np.array([1,2,3])

In [13]:
print(arr.shape)

(3,)


In [15]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr2d)
print(arr2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [19]:
arr4d = np.empty((2,3,4,5))
print(arr4d.shape)
print(arr4d)
print(arr4d[0,1])

(2, 3, 4, 5)
[[[[-0.00000000e+000 -0.00000000e+000  3.21142670e-322  0.00000000e+000
     0.00000000e+000]
   [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
     0.00000000e+000]
   [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  2.26062991e-314
     2.26062991e-314]
   [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
     0.00000000e+000]]

  [[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
     0.00000000e+000]
   [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
     0.00000000e+000]
   [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
     0.00000000e+000]
   [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
     0.00000000e+000]]

  [[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
     0.00000000e+000]
   [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
     0.00000000e+000]
   [ 0.00000000e+000  0.00000000e+000  0.00

In [22]:
print("середнє значення", np.mean(arr))
print(np.argmax(arr))
print(np.prod(3))

середнє значення 2.0
2
3


In [31]:
arrNew = np.random.randint(0,5, (3,2))
print(arrNew)
sum = np.sum(arrNew, axis=0)
print(sum)

[[4 2]
 [0 3]
 [4 1]]
[8 6]


In [32]:
arrNew.reshape(2,3)

array([[4, 2, 0],
       [3, 4, 1]])

In [33]:
# стовпці axis = 0
# рядки axis = 1

In [39]:
arr5 = np.array([1,2,3,4])
mask = np.array([True,True, False,False])
mask2 = (arr5 > 1) & (arr5 < 10)
print(arr5[mask])
print(arr5[mask2])

[1 2]
[2 3 4]
