In [5]:
import numpy as np
square_matrix = np.zeros(shape=(3,3))
print(square_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
orig = np.random.randint(0, 5 [2, 2])
I = np.eye(2)
print(orig * I)

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
/var/folders/g2/jdj1wm7n7lqg0315d1ylkc7xw_5p47/T/ipykernel_16893/442415841.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  orig = np.random.randint(0, 5 [2, 2])
/var/folders/g2/jdj1wm7n7lqg0315d1ylkc7xw_5p47/T/ipykernel_16893/442415841.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  orig = np.random.randint(0, 5 [2, 2])
/var/folders/g2/jdj1wm7n7lqg0315d1ylkc7xw_5p47/T/ipykernel_16893/442415841.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  orig = np.random.randint(0, 5 [2, 2])


TypeError: 'int' object is not subscriptable

In [7]:
B = np.array(
    [[2, 4, 2],
    [5, 7, 8],
    [0, 7, 9]
    ])
print(B.T)

[[2 5 0]
 [4 7 7]
 [2 8 9]]


In [8]:
B_inv = np.linalg.inv(B)
print(B_inv)

[[-0.07291667  0.22916667 -0.1875    ]
 [ 0.46875    -0.1875      0.0625    ]
 [-0.36458333  0.14583333  0.0625    ]]


In [ ]:
print(np.linalg.det(B))

-95.99999999999999


In [9]:
print(np.ones(len(B)).dot(B))

[ 7. 18. 19.]


In [16]:
np.dot(B, B_inv)

array([[1.00000000e+00, 0.00000000e+00, 2.77555756e-17],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 8.32667268e-17, 1.00000000e+00]])

In [17]:
B @ B_inv

array([[1.00000000e+00, 0.00000000e+00, 2.77555756e-17],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 8.32667268e-17, 1.00000000e+00]])

In [15]:
print(B.dot(B_inv))

[[1.00000000e+00 0.00000000e+00 2.77555756e-17]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 8.32667268e-17 1.00000000e+00]]
