# Модуль numpy

# Вправи

In [1]:
import numpy as np

1. Дано: одновимірний масив

In [2]:
arr = np.random.rand(1000)

Завдання: замінити всі елементи цього масиву, які більші за середнє цього масива на це середнє значення.

In [15]:
mean = np.mean(arr)
print(mean)
np.putmask(arr, arr > mean, mean)
print(arr)

0.5102312288331209
[0.01612291 0.51023123 0.51023123 0.45507818 0.51023123 0.14574825
 0.51023123 0.51023123 0.34318071 0.51023123 0.51023123 0.51023123
 0.51023123 0.51023123 0.51023123 0.51023123 0.51023123 0.06703118
 0.33894257 0.1635827  0.40785493 0.51023123 0.51023123 0.41883033
 0.51023123 0.51023123 0.32311378 0.17364734 0.26471944 0.51023123
 0.51023123 0.51023123 0.21747145 0.29464665 0.34370138 0.19350533
 0.10676877 0.51023123 0.51023123 0.4142617  0.38677067 0.33984673
 0.51023123 0.46295492 0.51023123 0.51023123 0.51023123 0.51023123
 0.51023123 0.51023123 0.51023123 0.51023123 0.4527464  0.51023123
 0.51023123 0.28198103 0.17833419 0.25247129 0.51023123 0.51023123
 0.51023123 0.51023123 0.51023123 0.01125237 0.01986417 0.32472173
 0.22516521 0.29263254 0.01407256 0.51023123 0.12361487 0.51023123
 0.08574294 0.19462984 0.51023123 0.51023123 0.12907468 0.51023123
 0.51023123 0.51023123 0.51023123 0.05718769 0.51023123 0.51023123
 0.51023123 0.51023123 0.51023123 0.0535023

2. Для масиву з попередньої задачі імплементувати сигмоїдну функцію:

$$y = \frac{1} {1 + e^{-x}}$$

In [20]:
x = np.random.rand(1000)

In [21]:
y = 1/(1 + np.exp(-x))
print(y)

[0.52807428 0.50227757 0.53803962 0.58213452 0.54017727 0.68261285
 0.6415641  0.66008795 0.50723594 0.70955551 0.62090325 0.6158211
 0.63636639 0.51509855 0.538147   0.55548776 0.62319596 0.58637606
 0.53163249 0.57192154 0.52906927 0.6002225  0.67617106 0.68369161
 0.57539613 0.53225023 0.64783206 0.68010061 0.52381182 0.67211267
 0.73067297 0.62515853 0.53511963 0.60598895 0.54261174 0.69763021
 0.58151909 0.59930398 0.61544288 0.64091999 0.71909681 0.66775997
 0.71144265 0.51389649 0.60322201 0.58736325 0.50087689 0.70656475
 0.55449479 0.53021694 0.68461444 0.59680514 0.53232617 0.5360635
 0.6822325  0.61206588 0.53377237 0.72963436 0.71742698 0.71697497
 0.57396698 0.72722707 0.6778842  0.51491141 0.73026987 0.50183405
 0.53847345 0.56216916 0.71318606 0.67803614 0.54473308 0.66055026
 0.5521119  0.69578054 0.60503927 0.65423842 0.58681153 0.5896333
 0.5650073  0.57530295 0.50947116 0.51875783 0.64302791 0.51905773
 0.68262007 0.54407544 0.70282508 0.66948425 0.65919341 0.5132551

3. Вирішити завдання про таблицю співробітників використовуючи numpy (вивести на екран інформацію про співробітників, прийнятих на роботу після 2012 року та з ЗП понад 2000; надрукувати можна без форматування)

In [24]:
workers_table = np.array([
    [1, 'B', 1000, 2013],
    [2, 'B', 1500, 2014],
    [3, 'B', 1800, 2012],
    [4, 'A', 2500, 2016],
    [5, 'A', 3500, 2017],
    [6, 'A', 4500, 2011],
], dtype=object)

mask = (workers_table[:,2] > 2000) & (workers_table[:,3] > 2012)
print(workers_table[mask])

[[4 'A' 2500 2016]
 [5 'A' 3500 2017]]


4. У таблиці співробітників з попередньої задачі, додати ще один стовпець, де записати різницю між ЗП співробітника та середньою ЗП усіх співробітників.

In [67]:
avg = np.average([workers_table[:,2]])
avgDiff = np.array([workers_table[:,2] - avg]).reshape(6,1)
print(np.append(workers_table, avgDiff, axis = 1))

[[1 'B' 1000 2013 -1466.6666666666665]
 [2 'B' 1500 2014 -966.6666666666665]
 [3 'B' 1800 2012 -666.6666666666665]
 [4 'A' 2500 2016 33.333333333333485]
 [5 'A' 3500 2017 1033.3333333333335]
 [6 'A' 4500 2011 2033.3333333333335]]


5. У таблиці співробітників знайти та вивести на екран мінімальний рік прийому на роботу в кожному департаменті.

In [96]:
print("У департаменті 'B' мінімальний рік прийому на роботу - ", np.min(workers_table[:,3], initial = 10000, where=workers_table[:,1] == 'B'))
print("У департаменті 'А' мінімальний рік прийому на роботу - ", np.min(workers_table[:,3], initial = 10000, where=workers_table[:,1] == 'A'))

У департаменті 'B' мінімальний рік прийому на роботу -  2012
У департаменті 'А' мінімальний рік прийому на роботу -  2011


6. Дана таблиця A

In [92]:
A = np.array([
    [2, 5, 8, 56],
    [4, 9, 1, 23],
    [6, 12, 84, 55]
])

Завдання: нормалізувати колонки (зробити так, щоб довжина векторів у колонках була 1)

In [99]:
# Підраховуємо суму кожного стовпця
sum = np.sum(A, axis = 0)

# Ділимо весь масив на рядок з сумами кожного стовпця
print(A/sum)

[[0.16666667 0.19230769 0.08602151 0.41791045]
 [0.33333333 0.34615385 0.01075269 0.17164179]
 [0.5        0.46153846 0.90322581 0.41044776]]
