# Вправи
(використовувати тільки матричні операції)

1. Отримати суму елементів та суму квадратів елементів вектора:

In [3]:
import numpy as np

In [4]:
v = np.array([1, 2, 3, 4, 5, 6])

In [5]:
# np.sum(v) не можна використовувати

In [6]:
# сума елементів вектора v
sum = np.ones(len(v)).dot(v)
print(sum)

# сума квадратів елементів вектора v
np.ones(len(v)).dot(v*v)

21.0


91.0

2. Для вектора попереднього завдання побудувати вектор, кожним елементом якого є середнє значення вектора.

In [7]:
mean = sum/len(v)
print(mean)
print(np.ones(len(v)) * mean)
print(np.array([mean for x in range(len(v))]))




3.5
[3.5 3.5 3.5 3.5 3.5 3.5]
[3.5 3.5 3.5 3.5 3.5 3.5]


3. Написати функцію, яка приймає на вхід довільну кількість матриць, перевіряє, чи можна їх перемножити, і якщо можна, то повертає розмірність результату (можна скористатися циклом). 

In [57]:
matrix1 = np.array([
    [12,7,3],
    [4,5,6],
    [7 ,8,9]])
matrix2 = np.array([
    [5,8,1],
    [6,7,3],
    [4,5,9]])

In [79]:
def matrix_mult(*args) -> int:
  # додаємо кількість аргументів, щоб стежити за останнім елементом
  length = len(args)

  # ініціюємо пустий масив
  res = {}
  current = args[0]
  # перевірити кінець матриці
  while length >= 2:
   for x in args:
    length -= 1
    next = args[args.index(x) + 1]
    if (current.shape[0] == next.shape[1]):
      # будуємо пусту матрицю для результату множення
      res = np.array([[0 for x in range(len(current))] for y in range(len(next))])
      # множимо матриці
      for a in range(len(current)):
          for j in range(len(next[0])):
            for b in range(len(next)):
              res[a][j] += x[a][b] * next[b][j]
      print(res)
      current = res
    else:
      continue
    
   return res.shape


print(matrix_mult(matrix1, matrix2))


[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

4.Обчислити вираз:

$$\sum_{i=1}^n(x_{i} - avg(x))^{2}$$

In [93]:
def sol(x, i = 1, *args):
  total = 0
  length = 0
  
  for i in args:
    total += i
    length += 1
    mean = total/length
    sum = (x - mean)*(x - mean)
  return sum

print(sol(1, 2, 3))

4.0


5. Вивести матрицю, яка при множенні на вектор зліва (Мх) приводить його до форми відхилення від середнього значення. Тобто, кожним елементом вектора-результату буде відповідний елемент вхідного вектора мінус середнє значення. Матриця М не повинна залежати від вхідного вектора x, а лише від його довжини. Іншими словами, для створення такої матриці має бути достатньо лише знання скільки в них елементів.

6. Розв'язати систему рівнянь (можна скористатися функцією кореня):

$$
47a^{2} + 71b - 2c = 3\\\
11b - 8c = 3\\\
a^{2} + b + c = 24\\\
$$